#port
server.port=8761
spring.application.name=service-registry

#Postgres
#spring.datasource.url=jdbc:postgresql://10.30.1.64:5432/releasex_dev_new
spring.datasource.url=jdbc:oracle:thin:@//104.242.248.205:1521/POCDB
spring.jpa.properties.hibernate.default_schema=releasex_dev_new_schema
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=releasexuser
spring.datasource.password=Welcome@123!8761
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#eureka server
# eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false